spring:
  application:
    name: service-ribbon
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8091/eureka

server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-methods: "*"
        allowed-origins: "*"
